global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'mlflow'
    static_configs:
      - targets: ['host.docker.internal:5000']
    metrics_path: '/prometheus_metrics'

  - job_name: 'training'
    static_configs:
      - targets: ['host.docker.internal:8000']

  - job_name: 'api'
    static_configs:
      - targets: ['host.docker.internal:5001']

  - job_name: 'streamlit_ui'
    metrics_path: '/_stcore/metrics' # Specific path for streamlit-extras
    static_configs:
      - targets: ['host.docker.internal:8001'] # Default Streamlit port
